import type { EducationEntry, WorkHistoryEntry } from "./types";

/** Employment history — sourced from CV; edit here only */
export const workHistory: WorkHistoryEntry[] = [
  {
    id: "softserve-2025",
    company: "SoftServe",
    role: "Full-Stack Engineer",
    rangeLabel: "June 2025 – February 2026",
    start: { year: 2025, month: 6 },
    end: { year: 2026, month: 2 },
    domain:
      "Enterprise Jira ecosystem—onboarding, product requirements, and scalable delivery with architects and stakeholders.",
    techStack: [
      "React",
      "TypeScript",
      "Node.js (NestJS)",
      "REST APIs",
      "OpenAPI",
      "MongoDB",
      "AWS",
      "OAuth 2.0 / OIDC",
      "Atlassian Jira APIs",
      "Jira",
      "Agile",
      "AI-assisted engineering (ChatGPT, Claude, Cursor)",
    ],
    teamSize: "30",
    contributions: [
      "Collaborated with solution architects on system design, scalability, integration complexity, and trade-offs.",
      "Improved onboarding flows by finding bottlenecks and optimizing journeys for usability.",
      "Translated business requirements into scalable technical solutions and system design.",
      "Designed and implemented backend APIs and frontend components in a Jira-integrated ecosystem.",
      "Participated in architectural reviews and feasibility assessments for enterprise clients.",
      "Resolved production issues to improve stability and reduce incident impact.",
      "Worked across engineering, product, and stakeholders for aligned delivery.",
    ],
  },
  {
    id: "honeycomb-2024",
    company: "HoneyComb Software",
    role: "Senior Full-Stack Developer",
    rangeLabel: "March 2024 – February 2025",
    start: { year: 2024, month: 3 },
    end: { year: 2025, month: 2 },
    domain:
      "AI-powered platform for Gas & Oil—structured extraction from large volumes of reports and documents.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Redux",
      "AG Grid",
      "Node.js (NestJS)",
      "Python services",
      "REST APIs",
      "OpenAPI",
      "MySQL (AWS RDS)",
      "AWS (ECS, ECR, S3, ALB)",
      "Docker",
      "OAuth 2.0 / OIDC",
      "LLM APIs (OpenAI, Anthropic, Azure OpenAI)",
      "RAG & document / structured extraction pipelines",
      "Embeddings, chunking & relevance tuning",
      "Prompt design, evals & guardrails for production",
      "Tool-calling & agentic workflows (where appropriate)",
      "AI-assisted engineering (ChatGPT, Claude, Cursor)",
      "Vector search (e.g. pgvector, managed vector DBs)",
    ],
    teamSize: "10",
    contributions: [
      "Designed and optimized data pipelines for structured information from large unstructured datasets.",
      "Refactored frontend architecture; scalable AG Grid data tables for large datasets.",
      "Redesigned DB schemas and optimized queries for latency and processing efficiency.",
      "Implemented OAuth authentication and role-based access control.",
      "Improved performance via backend request handling and frontend rendering tuning.",
      "Contributed to architectural discussions on scalability and maintainability.",
      "Resolved production issues through debugging and performance work.",
      "Used AI-assisted workflows (ChatGPT, Claude) to accelerate debugging, prototyping, and exploration.",
    ],
  },
  {
    id: "chi-2021",
    company: "CHI Software",
    role: "Senior Full-Stack Engineer",
    rangeLabel: "March 2021 – March 2024",
    start: { year: 2021, month: 3 },
    end: { year: 2024, month: 3 },
    domain:
      "Marketing, fintech, education, and media—performance, real-time features, and secure integrations.",
    techStack: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js (Express)",
      "REST APIs",
      "WebSockets (Socket.io)",
      "PostgreSQL",
      "MySQL (AWS RDS)",
      "MongoDB",
      "Redis",
      "AWS",
      "Docker",
      "CI/CD",
      "Okta (SSO)",
      "OAuth 2.0 / OIDC",
      "JWT & session hardening",
      "Stripe & payment flows",
      "Webhooks",
      "Third-party APIs",
      "AI-assisted engineering (ChatGPT, Claude, Cursor)",
    ],
    teamSize: "3–25 engineers (cross-functional)",
    contributions: [
      "Designed backend architecture and database schemas for scalable applications.",
      "Built data-intensive platforms with multiple third-party APIs; reduced latency.",
      "Implemented secure payment flows across web and mobile with reliability and consistency.",
      "Shipped real-time features with Socket.io.",
      "Integrated Okta SSO for security and access control.",
      "Optimized DB queries and external API usage.",
      "Contributed to architecture for scalability and less technical debt.",
      "Mentored engineers and participated in delivery planning.",
    ],
  },
  {
    id: "upplabs-2020",
    company: "Upplabs",
    role: "Frontend Engineer",
    rangeLabel: "December 2020 – March 2021",
    start: { year: 2020, month: 12 },
    end: { year: 2021, month: 3 },
    domain: "Video communications.",
    techStack: ["React Native", "Redux", "REST APIs", "WebSocket (basic)"],
    teamSize: "15",
    contributions: [
      "Built and optimized UI for a React Native app across devices.",
      "Implemented video calls, messaging, and profile management.",
      "Improved performance via rendering and state management.",
      "Integrated APIs and real-time features with backend engineers.",
    ],
  },
  {
    id: "massmedia-2020",
    company: "Massmedia Group",
    role: "Frontend Engineer",
    rangeLabel: "August 2020 – December 2020",
    start: { year: 2020, month: 8 },
    end: { year: 2020, month: 12 },
    domain: "Marketing websites.",
    techStack: [
      "HTML5",
      "CSS (Flexbox)",
      "SCSS",
      "JavaScript",
      "React",
      "Next.js",
      "Firestore",
      "Firebase",
    ],
    teamSize: "15",
    responsibilities: [
      "Aligned site strategies with marketing and business goals.",
      "Analyzed performance and user behaviour for improvements.",
      "Led site projects end-to-end for functionality and UX.",
      "Fixed issues and optimized systems for reliability.",
      "Shipped new features for evolving business needs.",
      "Collaborated with designers, developers, and content for consistency.",
    ],
  },
  {
    id: "eliftech-2019",
    company: "Eliftech",
    role: "Full-Stack Developer",
    rangeLabel: "March 2019 – August 2020",
    start: { year: 2019, month: 3 },
    end: { year: 2020, month: 8 },
    domain:
      "Wind power, e-commerce, marketing, healthcare & fitness, education.",
    techStack: [
      "HTML",
      "CSS",
      "SASS",
      "JavaScript",
      "Angular",
      "React",
      "Redux",
      "RxJS",
      "react-intl",
      "Node.js",
      "Express",
      "React Native",
      "Firebase",
      "MySQL (Sequelize)",
      "PostgreSQL",
      "Swagger",
      "GitHub",
      "Material UI",
      "Jira",
      "Trello",
      "AWS",
    ],
    teamSize: "1–15",
    responsibilities: [
      "Resolved issues and optimized existing systems.",
      "Built apps to optimize customer costs.",
      "Improved UI/UX.",
      "Customized HTML video player.",
      "Designed coherent frontend and backend architectures.",
      "Implemented multi-language support.",
      "Managed teams and delivered with Scrum.",
    ],
    accomplishments: [
      "Learned new technologies within about two weeks when needed.",
      "Delivered on tight deadlines.",
    ],
  },
  {
    id: "magisale-2018",
    company: "Magisale",
    role: "Full-Stack Developer",
    rangeLabel: "November 2018 – March 2019",
    start: { year: 2018, month: 11 },
    end: { year: 2019, month: 3 },
    domain: "E-commerce.",
    techStack: [
      "JavaScript (ES6)",
      "OOP",
      "Node.js (Express)",
      "Passport.js",
      "MongoDB (Mongoose)",
      "MySQL (Sequelize)",
      "Redis",
      "Bitbucket",
      "GitHub",
      "Jira",
      "Trello",
    ],
    teamSize: "8",
    responsibilities: [
      "Built site infrastructure and intuitive UI.",
      "Implemented transactions and admin tools for listings, inventory, and orders.",
      "Added reviews and recommendations.",
      "Responsive design across devices.",
    ],
    accomplishments: [
      "Mentored three trainees to junior level.",
      "Delivered an MVP in three months.",
    ],
  },
  {
    id: "softbistro-2018",
    company: "Softbistro",
    role: "Full-Stack Developer (internship)",
    rangeLabel: "June 2018 – August 2018",
    start: { year: 2018, month: 6 },
    end: { year: 2018, month: 8 },
    domain: "Marketing — Work.ua parser.",
    techStack: ["HTML5", "CSS3", "JavaScript (ES5)", "PHP", "Bitbucket"],
    teamSize: "3–5",
    responsibilities: [
      "Built frontend and backend for a Work.ua parser.",
      "Designed UI and mitigated PHP risks (SQL injection) with prepared statements and validation.",
      "Tested thoroughly and fixed issues across full-stack, security, and UI.",
    ],
  },
  {
    id: "rexsoft-2018",
    company: "Rexsoft",
    role: "Frontend Engineer (internship)",
    rangeLabel: "May 2018 – June 2018",
    start: { year: 2018, month: 5 },
    end: { year: 2018, month: 6 },
    domain: "Marketing — company landing pages.",
    techStack: [
      "HTML5 (Pug)",
      "CSS3 (flexbox, grid, Bootstrap)",
      "Sass",
      "JavaScript (ES5/ES6)",
      "Gulp",
      "Bitbucket",
      "GitHub",
    ],
    teamSize: "3–5",
    responsibilities: [
      "Created landing pages tailored to requirements, design, copy, and UX to support brand and conversions.",
    ],
  },
  {
    id: "freelancehunt-2018",
    company: "Freelancehunt",
    role: "Frontend Engineer",
    rangeLabel: "February 2018 – May 2018",
    start: { year: 2018, month: 2 },
    end: { year: 2018, month: 5 },
    domain: "Marketing, e-commerce, logistics landing pages.",
    techStack: [
      "HTML5 (Pug)",
      "CSS3 (Flexbox, Grid, Bootstrap, Foundation)",
      "SASS",
      "JavaScript ES5",
      "MySQL",
      "MongoDB (Mongoose)",
      "PHP (Yii2, Laravel)",
      "Gulp",
      "GitHub",
      "Bitbucket",
    ],
    teamSize: "3–5",
    responsibilities: [
      "Built landing pages per industry—design, copy, and UX for leads, products, or logistics services.",
    ],
  },
];

export const educationHistory: EducationEntry[] = [
  {
    id: "dnu-bachelor",
    institution: "Vasyl Stus Donetsk National University",
    location: "Vinnytsia, Ukraine",
    field: "Computer Science",
    degree: "Bachelor's degree",
    rangeLabel: "2018 – 2019",
  },
  {
    id: "dnu-master",
    institution: "Vasyl Stus Donetsk National University",
    location: "Vinnytsia, Ukraine",
    field: "Computer Science",
    degree: "Master's degree",
    rangeLabel: "2019 – 2022",
  },
  {
    id: "khmel-cyber",
    institution: "Khmelnytskyi National University",
    location: "Khmelnytskyi, Ukraine",
    field: "Cybersecurity",
    degree: "Master's degree",
    rangeLabel: "2022 – 2024",
  },
];

export const languageSkills = [
  { language: "English", level: "Upper intermediate" },
  { language: "Ukrainian", level: "Native" },
] as const;
